using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Editor window: reads data/mazes.json (generated by scripts/generate_mazes.ipynb)
/// and instantiates wall and corner prefabs in the scene for a chosen room.
///
/// Outer perimeter walls are not placed — they are provided by the room geometry.
/// Corner pieces are placed at every grid vertex where at least one interior
/// horizontal wall and at least one interior vertical wall meet.
///
/// Menu: Tools/DreamGuard/Maze Generator
/// </summary>
public class MazeGeneratorWindow : EditorWindow
{
    // ── JSON data classes ─────────────────────────────────────────────────────

    [Serializable]
    private class WallSegmentData
    {
        public float width;
        public float height;
        public float thickness;
    }

    [Serializable]
    private class WallEntryData
    {
        public float  x;
        public float  z;
        public int    rotation_y;
        public string axis;
    }

    [Serializable]
    private class MazeData
    {
        public string room_id;
        public int    seed;
        public int    grid_nx;
        public int    grid_nz;
        public float  cell_width;
        public float  cell_length;
        public int    entrance_col;
        public int    exit_col;
        public WallEntryData[] walls;
    }

    [Serializable]
    private class MazesFile
    {
        public WallSegmentData wall_segment;
        public MazeData[]      mazes;
    }

    // ── Wall variant ──────────────────────────────────────────────────────────

    [Serializable]
    private class WallVariant
    {
        public GameObject prefab;
        public float      weight = 1f;
    }

    // ── Window state ──────────────────────────────────────────────────────────

    [SerializeField] private List<WallVariant> _wallVariants    = new List<WallVariant>();
    [SerializeField] private GameObject        _cornerPrefab;
    [SerializeField] private Transform         _parentTransform;

    private Vector2 _variantsScroll;

    private MazesFile _mazesFile;
    private string[]  _roomIds = Array.Empty<string>();
    private int       _selectedRoomIndex;

    private string      _statusMessage = "";
    private MessageType _statusType    = MessageType.Info;

    // ── Menu ──────────────────────────────────────────────────────────────────

    [MenuItem("Tools/DreamGuard/Maze Generator")]
    public static void ShowWindow()
    {
        var w = GetWindow<MazeGeneratorWindow>("Maze Generator");
        w.minSize = new Vector2(420, 480);
        w.LoadMazesJson();
    }

    private void OnEnable() => LoadMazesJson();

    // ── GUI ───────────────────────────────────────────────────────────────────

    private void OnGUI()
    {
        EditorGUILayout.Space(6);
        EditorGUILayout.LabelField("DreamGuard — Maze Generator", EditorStyles.boldLabel);
        EditorGUILayout.Space(4);

        DrawDataSourceSection();
        EditorGUILayout.Space(8);

        if (_mazesFile == null || _mazesFile.mazes == null || _mazesFile.mazes.Length == 0)
        {
            EditorGUILayout.HelpBox(
                "No maze data loaded. Run  scripts/generate_mazes.ipynb  to produce data/mazes.json.",
                MessageType.Error);
            return;
        }

        DrawRoomSection();
        EditorGUILayout.Space(8);
        DrawWallVariantsSection();
        EditorGUILayout.Space(8);
        DrawCornerSection();
        EditorGUILayout.Space(8);
        DrawSceneSection();
        EditorGUILayout.Space(10);
        DrawGenerateButton();

        if (!string.IsNullOrEmpty(_statusMessage))
        {
            EditorGUILayout.Space(4);
            EditorGUILayout.HelpBox(_statusMessage, _statusType);
        }
    }

    private void DrawDataSourceSection()
    {
        EditorGUILayout.LabelField("Data Source", EditorStyles.miniBoldLabel);
        string jsonPath  = GetMazesJsonPath();
        bool   jsonFound = File.Exists(jsonPath);
        EditorGUILayout.HelpBox(
            jsonFound ? jsonPath : $"Not found:\n{jsonPath}",
            jsonFound ? MessageType.None : MessageType.Warning);
        if (GUILayout.Button("Reload mazes.json"))
            LoadMazesJson();
    }

    private void DrawRoomSection()
    {
        EditorGUILayout.LabelField("Room", EditorStyles.miniBoldLabel);
        _selectedRoomIndex = EditorGUILayout.Popup("Maze (room_id)", _selectedRoomIndex, _roomIds);

        var maze = _mazesFile.mazes[_selectedRoomIndex];
        EditorGUI.indentLevel++;
        EditorGUILayout.LabelField(
            $"Grid: {maze.grid_nz}\u202f\u00d7\u202f{maze.grid_nx}   Seed: {maze.seed}   Walls: {maze.walls?.Length ?? 0}",
            EditorStyles.miniLabel);
        EditorGUILayout.LabelField(
            $"Cell: {maze.cell_width}\u202f\u00d7\u202f{maze.cell_length}\u202fm   Entrance col: {maze.entrance_col}   Exit col: {maze.exit_col}",
            EditorStyles.miniLabel);
        EditorGUI.indentLevel--;
    }

    private void DrawWallVariantsSection()
    {
        EditorGUILayout.LabelField("Wall Variants", EditorStyles.miniBoldLabel);

        float totalWeight = 0f;
        foreach (var v in _wallVariants)
            if (v.prefab != null) totalWeight += Mathf.Max(0f, v.weight);

        float listHeight = Mathf.Clamp(_wallVariants.Count * 22f + 4f, 22f, 110f);
        _variantsScroll = EditorGUILayout.BeginScrollView(_variantsScroll,
            GUILayout.Height(listHeight));

        for (int i = 0; i < _wallVariants.Count; i++)
        {
            var v = _wallVariants[i];
            EditorGUILayout.BeginHorizontal();

            v.prefab = (GameObject)EditorGUILayout.ObjectField(
                v.prefab, typeof(GameObject), false, GUILayout.Width(160));

            EditorGUILayout.LabelField("Weight", GUILayout.Width(46));
            v.weight = EditorGUILayout.FloatField(Mathf.Max(0f, v.weight), GUILayout.Width(48));

            float prob = (totalWeight > 0f && v.prefab != null)
                ? v.weight / totalWeight * 100f : 0f;
            EditorGUILayout.LabelField($"{prob:F1}%", EditorStyles.miniLabel, GUILayout.Width(40));

            if (GUILayout.Button("\u2212", GUILayout.Width(20)))
            {
                _wallVariants.RemoveAt(i);
                Repaint();
                EditorGUILayout.EndHorizontal();
                break;
            }

            EditorGUILayout.EndHorizontal();
        }

        EditorGUILayout.EndScrollView();

        if (GUILayout.Button("+ Add Wall Variant"))
            _wallVariants.Add(new WallVariant { weight = 1f });

        if (!HasAnyValidVariant())
            EditorGUILayout.HelpBox("Add at least one wall variant with a prefab and weight > 0.", MessageType.Warning);
    }

    private void DrawCornerSection()
    {
        EditorGUILayout.LabelField("Corners", EditorStyles.miniBoldLabel);
        _cornerPrefab = (GameObject)EditorGUILayout.ObjectField(
            "Corner Prefab (optional)", _cornerPrefab, typeof(GameObject), false);
        EditorGUI.indentLevel++;
        EditorGUILayout.LabelField(
            "Placed at grid vertices where interior horizontal and vertical walls meet.",
            EditorStyles.miniLabel);
        EditorGUI.indentLevel--;
    }

    private void DrawSceneSection()
    {
        EditorGUILayout.LabelField("Scene", EditorStyles.miniBoldLabel);
        _parentTransform = (Transform)EditorGUILayout.ObjectField(
            "Parent Transform", _parentTransform, typeof(Transform), true);
        EditorGUILayout.HelpBox(
            _parentTransform == null
                ? "No parent — container placed at scene root."
                : $"Container will be a child of \"{_parentTransform.name}\".",
            MessageType.None);
    }

    private void DrawGenerateButton()
    {
        using (new EditorGUI.DisabledGroupScope(!HasAnyValidVariant()))
        {
            if (GUILayout.Button("Generate Maze", GUILayout.Height(32)))
                GenerateMaze();
        }
    }

    private bool HasAnyValidVariant()
    {
        foreach (var v in _wallVariants)
            if (v.prefab != null && v.weight > 0f) return true;
        return false;
    }

    // ── JSON ──────────────────────────────────────────────────────────────────

    // Application.dataPath = …/playground/unity/DreamGuard/Assets
    // Four directories up is the repo root, then data/mazes.json.
    private static string GetMazesJsonPath() =>
        Path.GetFullPath(Path.Combine(Application.dataPath, "../../../../data/mazes.json"));

    private void LoadMazesJson()
    {
        string path = GetMazesJsonPath();
        if (!File.Exists(path))
        {
            _mazesFile = null;
            _roomIds   = Array.Empty<string>();
            Debug.LogWarning($"[MazeGenerator] mazes.json not found: {path}");
            return;
        }

        try
        {
            string json = File.ReadAllText(path);
            _mazesFile  = JsonUtility.FromJson<MazesFile>(json);

            if (_mazesFile?.mazes == null)
            {
                Debug.LogError("[MazeGenerator] mazes.json parsed but 'mazes' array is null.");
                _mazesFile = null;
                _roomIds   = Array.Empty<string>();
                return;
            }

            _roomIds = new string[_mazesFile.mazes.Length];
            for (int i = 0; i < _mazesFile.mazes.Length; i++)
                _roomIds[i] = _mazesFile.mazes[i].room_id;

            _selectedRoomIndex = Mathf.Clamp(_selectedRoomIndex, 0, _mazesFile.mazes.Length - 1);
            Debug.Log($"[MazeGenerator] Loaded {_mazesFile.mazes.Length} maze(s) from {path}");
        }
        catch (Exception e)
        {
            Debug.LogError($"[MazeGenerator] Exception reading mazes.json: {e.Message}");
            _mazesFile = null;
            _roomIds   = Array.Empty<string>();
        }
    }

    // ── Generation ────────────────────────────────────────────────────────────

    private void GenerateMaze()
    {
        var maze = _mazesFile.mazes[_selectedRoomIndex];

        if (maze.walls == null || maze.walls.Length == 0)
        {
            SetStatus($"No wall data for '{maze.room_id}'.", MessageType.Error);
            return;
        }

        var pool = BuildVariantPool(out float totalWeight);
        if (pool.Count == 0 || totalWeight <= 0f)
        {
            SetStatus("No valid wall variants (need at least one prefab with weight > 0).", MessageType.Error);
            return;
        }

        // Seeded by maze seed for deterministic texture distribution.
        var rng = new System.Random(maze.seed);

        Undo.SetCurrentGroupName("Generate Maze");
        int undoGroup = Undo.GetCurrentGroup();

        // ── Container ─────────────────────────────────────────────────────────
        string containerName = $"Maze_{maze.room_id}";

        if (_parentTransform != null)
        {
            Transform existing = _parentTransform.Find(containerName);
            if (existing != null) Undo.DestroyObjectImmediate(existing.gameObject);
        }
        else
        {
            GameObject existing = GameObject.Find(containerName);
            if (existing != null) Undo.DestroyObjectImmediate(existing);
        }

        var containerGo = new GameObject(containerName);
        Undo.RegisterCreatedObjectUndo(containerGo, "Generate Maze");
        if (_parentTransform != null)
            containerGo.transform.SetParent(_parentTransform, worldPositionStays: false);

        // ── Reconstruct interior wall grid from JSON positions ─────────────────
        //
        // h_walls[i, j]: horizontal wall on south edge of row i, col j
        //   center in JSON: x = (j+0.5)*cw - hw,  z = i*cl - hl
        //   perimeter when i == 0  (z == -hl)  or  i == nz  (z == +hl)
        //
        // v_walls[i, j]: vertical wall on west edge of col j, row i
        //   center in JSON: x = j*cw - hw,  z = (i+0.5)*cl - hl
        //   perimeter when j == 0  (x == -hw)  or  j == nx  (x == +hw)
        //
        // Z is negated on placement (row-0=south in the notebook = high-Z in Unity).

        int nx = maze.grid_nx;
        int nz = maze.grid_nz;
        float cw = maze.cell_width;
        float cl = maze.cell_length;
        float hw = nx * cw / 2f;
        float hl = nz * cl / 2f;
        const float eps = 0.05f;

        // Boolean arrays tracking which interior wall segments are present.
        bool[,] hWalls = new bool[nz + 1, nx]; // [row boundary, col]
        bool[,] vWalls = new bool[nz, nx + 1]; // [row, col boundary]

        foreach (var w in maze.walls)
        {
            if (w.axis == "h")
            {
                // Perimeter: z == ±hl
                if (Mathf.Abs(Mathf.Abs(w.z) - hl) < eps) continue;
                int ri = Mathf.RoundToInt((w.z + hl) / cl);
                int rj = Mathf.RoundToInt((w.x + hw) / cw - 0.5f);
                if (ri >= 0 && ri <= nz && rj >= 0 && rj < nx)
                    hWalls[ri, rj] = true;
            }
            else // v
            {
                // Perimeter: x == ±hw
                if (Mathf.Abs(Mathf.Abs(w.x) - hw) < eps) continue;
                int rj = Mathf.RoundToInt((w.x + hw) / cw);
                int ri = Mathf.RoundToInt((w.z + hl) / cl - 0.5f);
                if (ri >= 0 && ri < nz && rj >= 0 && rj <= nx)
                    vWalls[ri, rj] = true;
            }
        }

        // ── Walls ─────────────────────────────────────────────────────────────
        var wallsGo = new GameObject("Walls");
        Undo.RegisterCreatedObjectUndo(wallsGo, "Generate Maze");
        wallsGo.transform.SetParent(containerGo.transform, worldPositionStays: false);

        int wallCount = 0;

        // Place h walls (interior)
        for (int i = 0; i <= nz; i++)
        {
            for (int j = 0; j < nx; j++)
            {
                if (!hWalls[i, j]) continue;
                float wx = (j + 0.5f) * cw - hw;
                float wz = -(i * cl - hl);   // negate Z
                PlaceWall(wallsGo.transform, wx, wz, 0, $"Wall_h_{wallCount:D3}",
                    pool, totalWeight, rng);
                wallCount++;
            }
        }

        // Place v walls (interior)
        for (int i = 0; i < nz; i++)
        {
            for (int j = 0; j <= nx; j++)
            {
                if (!vWalls[i, j]) continue;
                float wx = j * cw - hw;
                float wz = -((i + 0.5f) * cl - hl);   // negate Z
                PlaceWall(wallsGo.transform, wx, wz, 90, $"Wall_v_{wallCount:D3}",
                    pool, totalWeight, rng);
                wallCount++;
            }
        }

        // ── Corners ───────────────────────────────────────────────────────────
        //
        // A corner is placed at grid vertex (i, j) when at least one interior
        // h wall and at least one interior v wall meet at that vertex.
        //
        // Adjacent h walls at vertex (i, j): hWalls[i, j-1] or hWalls[i, j]
        // Adjacent v walls at vertex (i, j): vWalls[i-1, j] or vWalls[i, j]

        int cornerCount = 0;

        if (_cornerPrefab != null)
        {
            var cornersGo = new GameObject("Corners");
            Undo.RegisterCreatedObjectUndo(cornersGo, "Generate Maze");
            cornersGo.transform.SetParent(containerGo.transform, worldPositionStays: false);

            for (int i = 0; i <= nz; i++)
            {
                for (int j = 0; j <= nx; j++)
                {
                    bool adjH = (j > 0  && hWalls[i, j - 1])
                             || (j < nx && hWalls[i, j]);
                    bool adjV = (i > 0  && vWalls[i - 1, j])
                             || (i < nz && vWalls[i, j]);

                    if (!adjH || !adjV) continue;

                    float cx = j * cw - hw;
                    float cz = -(i * cl - hl);   // negate Z

                    var cornerGo = (GameObject)PrefabUtility.InstantiatePrefab(
                        _cornerPrefab, cornersGo.transform);
                    Undo.RegisterCreatedObjectUndo(cornerGo, "Generate Maze");
                    cornerGo.transform.localPosition = new Vector3(cx, 0f, cz);
                    cornerGo.transform.localRotation = Quaternion.identity;
                    cornerGo.name = $"Corner_{i}_{j}";
                    cornerCount++;
                }
            }
        }

        Undo.CollapseUndoOperations(undoGroup);

        string msg = $"Generated {wallCount} wall(s)"
                   + (cornerCount > 0 ? $" + {cornerCount} corner(s)" : "")
                   + $" for '{maze.room_id}'.";
        SetStatus(msg, MessageType.Info);
        Debug.Log($"[MazeGenerator] {msg}");

        Selection.activeGameObject = containerGo;
        EditorGUIUtility.PingObject(containerGo);
    }

    private void PlaceWall(Transform parent, float x, float z, int rotY, string name,
        List<(GameObject prefab, float cumulative)> pool, float totalWeight, System.Random rng)
    {
        var prefab = SampleVariant(pool, totalWeight, rng);
        var go     = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent);
        Undo.RegisterCreatedObjectUndo(go, "Generate Maze");
        go.transform.localPosition = new Vector3(x, 0f, z);
        go.transform.localRotation = Quaternion.Euler(0f, rotY, 0f);
        go.name = name;
    }

    // ── Weighted sampling ─────────────────────────────────────────────────────

    private List<(GameObject prefab, float cumulative)> BuildVariantPool(out float totalWeight)
    {
        var pool = new List<(GameObject, float)>();
        totalWeight = 0f;
        foreach (var v in _wallVariants)
        {
            if (v.prefab == null || v.weight <= 0f) continue;
            totalWeight += v.weight;
            pool.Add((v.prefab, totalWeight));
        }
        return pool;
    }

    private static GameObject SampleVariant(
        List<(GameObject prefab, float cumulative)> pool, float totalWeight, System.Random rng)
    {
        float roll = (float)(rng.NextDouble() * totalWeight);
        foreach (var (prefab, cumulative) in pool)
            if (roll < cumulative) return prefab;
        return pool[pool.Count - 1].prefab;
    }

    // ─────────────────────────────────────────────────────────────────────────

    private void SetStatus(string msg, MessageType type)
    {
        _statusMessage = msg;
        _statusType    = type;
        Repaint();
    }
}
